// eslint-disable-next-line no-restricted-imports
export {
  LayoutOutlined,
  FormOutlined,
  UnorderedListOutlined,
  InsertRowAboveOutlined,
  CloseCircleFilled,
  EyeOutlined,
  DesktopOutlined,
  MobileOutlined,
  CheckCircleOutlined,
  UsergroupAddOutlined,
  FileSyncOutlined,
  EditOutlined,
  VideoCameraOutlined,
  PictureOutlined,
  UserOutlined,
  PictureFilled,
  PlusOutlined,
  CloseOutlined,
  InfoCircleOutlined,
  MonitorOutlined,
  FolderOpenFilled,
  ProfileOutlined,
  ShareAltOutlined,
  UserSwitchOutlined,
  SettingOutlined,
  HistoryOutlined,
  FolderFilled,
} from "@ant-design/icons";
